### ISSUE TITLE
Submit paper

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/foss4g22#1]
Heads-up @temospena the MVP is in there. Any ideas welcome, feel free to push directly or PRs, looking forward to submitting this.

Also heads-up @dabreegster, invited you to the repo also, no expectation of contribution as you have loads on your plate these weeks but any general ideas welcome!

Many thanks!

**Comment by Robinlovelace** [comment]
P.s. updated deadline is 11th June which is sooo much better than what we thought it was, today :scream:

**Comment by temospena** [comment]
having trouble putting the addresses in 3 separated lines.
